import Document, { Html, Head, Main, NextScript } from 'next/document';
import Script from 'next/script';
class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }
  render() {
    return (
      <Html lang="en">
        <Head>
        <meta name="deScription" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="author" content="Creativeitem" />
        <meta name="keywords" content="LMS,Learning Management System,Creativeitem,demo,hello,How are you" />
        <meta name="deScription" content="Study any topic, anytime. explore thousands of courses for the lowest price ever!" />
        <meta property="og:title" content="Home" />
        <meta property="og:image" content="uploads/system/home-1.png" />
        <meta property="og:url" content="index.html" />
        <meta property="og:type" content="Learning management system" />
        <link rel="icon" href="uploads/system/1268adfb5db8c00c75b37961e8a9b787.png" type="image/x-icon" />
        <link rel="apple-touch-icon" sizes="180x180" href="uploads/system/1268adfb5db8c00c75b37961e8a9b787.png" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/all.min.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/bootstrap.min.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/jquery.webui-popover.min.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/h-2-carousel.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/jquery.webui-popover.min.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/nice-select.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/owl.theme.default.min.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/slick-theme.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/slick.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/style.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/new-style.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/responsive.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/summernote-0.8.20-dist/summernote-lite.min.css" />
        <link rel="stylesheet" href="assets/global/tagify/tagify.css" />
        <link rel="stylesheet" href="assets/global/toastr/toastr.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/animate.min.css" />
        <link rel="stylesheet" href="assets/frontend/default-new/css/custom.css" />

        
        </Head>
        <body>
          <Main />
          <NextScript/>
          {/* <Script src="assets/frontend/default-new/js/bootstrap.bundle.min.js" />
    <Script src="assets/frontend/default-new/js/berli.js" />
    <Script src="assets/frontend/default-new/js/course.js" />
    <Script src="assets/frontend/default-new/js/jquery.meanmenu.min.js" />
    <Script src="assets/frontend/default-new/js/jquery.nice-select.min.js" />
    <Script src="assets/frontend/default-new/js/jquery.webui-popover.min.js" />
    <Script src="assets/frontend/default-new/js/owl.carousel.min.js" />
    <Script src="assets/frontend/default-new/js/Script-2.js" />
    <Script src="assets/frontend/default-new/js/slick.min.js" />
    <Script src="assets/frontend/default-new/js/venobox.min.js" />
    <Script src="assets/frontend/default-new/js/wow.min.js" />
    <Script src="assets/frontend/default-new/js/Script.js" />
    <Script src="assets/frontend/default-new/summernote-0.8.20-dist/summernote-lite.min.js" />
    <Script src="assets/global/toastr/toastr.min.js" />
    <Script src="assets/global/jquery-form/jquery.form.min.js" />
    <Script src="assets/global/tagify/jquery.tagify.js" /> */}
        </body>
      </Html>
    );
  }
}

export default MyDocument;
